### ISSUE TITLE
Mix.install not working on Livebook v0.10.0 

### ISSUE THREAD

**Issue by ggerico** [jeregrine/Easel#1]
the setup doesn't work properly on Livebook V.0.10.0

``` elixir
Mix.install(
  [
    {:kino_canvas, github: "jeregrine/kino_canvas"}
  ]
)
```
it outputs this message error
```
Unknown output format: %{type: :terminal_text, chunk: false, text: "\e[34m:ok\e[0m"}. If you're using Kino,
you may want to update Kino and Livebook to the latest version.
```

**Comment by axler8r** [comment]
I have the same issue. I am working through Machine Learning in Elixir.

I am running Livebook in docker (on my Linux and Windows box) with the following command:

```shell
docker run --name ElixirML --rm --publish 8080:8080 --publish 8081:8081 --mount 'type=volume,source=ElixirMLData,destination=/data' --detach ghcr.io/livebook-dev/livebook:latest
```

and when I run `Mix.install/2` with the following dependency list:

```Elixir
Mix.install([
  {:scholar, "~> 0.2"},
  {:nx, "~> 0.6"},
  {:exla, "~> 0.6"},
  {:vega_lite, "~> 0.1"},
  {:kino_vega_lite, "~> 0.1"},
  {:scidata, "~> 0.1"}
])
```

if fails with:

"Unknown output format: %{type: :terminal_text, text: "\e[34m:ok\e[0m", chunk: false}. If you're using Kino, you may want to update Kino and Livebook to the latest version."

If I remove `{:kino_vega_lite, "~> 0.1"}` the error goes away.

**Comment by ggerico** [comment]
I have updated Livebook to v0.11.2, and it's working now ~
